config/routes.rb
Rails.application.routes.draw do
  root 'my/photos#index'
  namespace :my do
    resources :photos, only: %i[new create] do
      resources :tweets, only: %i[create], module: :photos
    end
  end
  namespace :oauth do
    get :authorize, to: 'authorize'
    get :callback, to: 'callback'
  end
  resource :session, only: %i[show new edit create update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  validates :title, presence: true, length: { maximum: 30 }
  validate :image_presence

  private

  def image_presence
    errors.add(:image, 'をアップロードしてください') unless image.attached?
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :user_id, presence: true, uniqueness: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  before_action :require_authentication

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**)
      skip_before_action(:require_authentication, **)
    end
  end

  private

  def authenticated?
    resume_session
  end

  def require_authentication
    resume_session || request_authentication
  end

  def resume_session
    Current.session ||= find_session_by_cookie
  end

  def find_session_by_cookie
    Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
  end

  def request_authentication
    session[:return_to_after_authenticating] = request.url
    redirect_to new_session_path
  end

  def after_authentication_url
    session.delete(:return_to_after_authenticating) || root_url
  end

  def start_new_session_for(user)
    user.sessions.create!.tap do |session|
      Current.session = session
      cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
    end
  end

  def terminate_session
    Current.session.destroy
    cookies.delete(:session_id)
  end
end

app/controllers/my/photos/tweets_controller.rb
class My::Photos::TweetsController < ApplicationController
  def create
    @photo = Current.user.photos.find(params[:photo_id])
    uri = URI('http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/api/tweets')
    http = Net::HTTP.new(uri.host, uri.port)
    http.request_post(uri.request_uri, URI.encode_www_form({ text: @photo.title, url: url_for(@photo.image) }),
                      Authorization: "Bearer #{session[:access_token]}")
    redirect_to root_path, notice: 'ツイートアプリに投稿しました'
  end
end

app/controllers/my/photos_controller.rb
class My::PhotosController < ApplicationController
  def index
    @photos = Current.user.photos.order(created_at: :desc)
  end

  def new
    @photo = Current.user.photos.build
  end

  def create
    @photo = Current.user.photos.build(photo_params)

    if @photo.save
      redirect_to root_path, notice: '投稿しました'
    else
      render :new, status: :unprocessable_content
    end
  end

  private

  def photo_params
    params.expect(photo: %i[title image])
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def authorize
    request_params =
      {
        scope: 'write_tweet',
        redirect_uri: Rails.application.credentials.my_tweet_app[:redirect_uri],
        client_id: Rails.application.credentials.my_tweet_app[:client_id],
        response_type: 'code',
      }

    redirect_to "http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/oauth/authorize?#{URI.encode_www_form(request_params)}",
                allow_other_host: true
  end

  def callback
    request_params =
      {
        grant_type: 'authorization_code',
        code: params[:code],
        client_id: Rails.application.credentials.my_tweet_app[:client_id],
        client_secret: Rails.application.credentials.my_tweet_app[:client_secret],
        redirect_uri: Rails.application.credentials.my_tweet_app[:redirect_uri],
      }
    uri = URI('http://unifa-recruit-my-tweet-app.ap-northeast-1.elasticbeanstalk.com/oauth/token')
    http = Net::HTTP.new(uri.host, uri.port)
    response = http.request_post(uri.request_uri, URI.encode_www_form(request_params), headers)
    session[:access_token] = JSON.parse(response.body)['access_token']

    redirect_to root_path, notice: 'MyTweetApp連携しました'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[new create]

  def new
  end

  def create
    if (user = User.authenticate_by(params.permit(:user_id, :password)))
      start_new_session_for user
      redirect_to after_authentication_url, notice: 'ログインしました'
    else
      redirect_to new_session_path, alert: 'ログインに失敗しました'
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path, notice: 'ログアウトしました'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def can_tweet?
    session[:access_token].present?
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Photo And Tweet"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
  %body
    .container
      = tag.div(flash[:alert], style: "color:red") if flash[:alert]
      = tag.div(flash[:notice], style: "color:green") if flash[:notice]
      .text-end
        - if authenticated?
          = button_to 'ログアウト', session_path, method: :delete, class: 'btn btn-outline-dark'
      = yield

app/views/my/photos/index.html.haml
%h1 写真一覧

.my-4
  %div= link_to 'MyTweetAPPと連携', oauth_authorize_path, class: 'btn btn-outline-secondary my-1'
  %div= link_to '写真アップロード', new_my_photo_path, class: 'btn btn-outline-secondary my-1'
.row
  - @photos.with_attached_image.each do |photo|
    .col-4
      = photo.title
      .w-75= image_tag photo.image.variant(resize_to_fill: [200, 200])
      - if can_tweet?
        = button_to 'ツイートする', my_photo_tweets_path(photo), class: 'btn btn-small btn-outline-secondary'

app/views/my/photos/new.html.haml
%h1 写真アップロード

= bootstrap_form_with model: [:my, @photo], local: true do |f|
  = f.text_field :title, label: 'タイトル', autofocus: true, maxlength: 30
  = f.file_field :image, label: '写真', required: true
  = f.submit '投稿する'

= link_to 'キャンセル', root_path, class: 'mt-4'

app/views/shared/_form_error.html.haml
- if object.errors.any?
  %div{style: "color:red"}
    %p 下記のエラーを確認してください
    %ul
      - object.errors.each do |error|
        %li= error.full_message